### ISSUE TITLE
[bug] file_chooser is remove in office resp

### ISSUE THREAD

**Issue by UniqueDing** [mabDc/eso#19]

**Comment by mabDc** [comment]
you can replace with
>   file_chooser: ^0.1.6

ps: `file_chooser` is the plugin for selecting file in desktop(windows, mac, linux)
      you can find other plugin to achieve the goal

**Comment by UniqueDing** [comment]
thanks but can help me other problem
I don't understand flutter....
my os: arch linux
Flutter 1.26.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 63062a6443 (4 weeks ago) • 2020-12-13 23:19:13 +0800
Engine • revision 4797b06652
Tools • Dart 2.12.0 (build 2.12.0-141.0.dev)

**I changed intl:^0.16.1 to intl:0.17.0-nullsafety.2**

then
```bash
/opt/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/opt/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies
-Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --packages /home/uniqueding/Github/eso/.dart_tool/package_config.json
--output-dill /home/uniqueding/Github/eso/.dart_tool/flutter_build/7a9dc904406dc0b7a21de6335bb2fe1e/app.dill --depfile
/home/uniqueding/Github/eso/.dart_tool/flutter_build/7a9dc904406dc0b7a21de6335bb2fe1e/kernel_snapshot.d package:eso/main.dart
[   +1 ms] [+3975 ms] lib/ui/edit/local_cupertion_delegate.dart:25:7: Error: The non-abstract class '_DefaultCupertinoLocalizations' is
missing implementations for these members:
[        ] [   +3 ms]  - CupertinoLocalizations.searchTextFieldPlaceholderLabel
[        ] [        ] Try to either
[        ] [        ]  - provide an implementation,
[        ] [        ]  - inherit an implementation from a superclass or mixin,
[        ] [        ]  - mark the class as abstract, or
[        ] [        ]  - provide a 'noSuchMethod' implementation.
[        ] [        ] class _DefaultCupertinoLocalizations extends CupertinoLocalizations {
[        ] [        ]       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [        ] /opt/flutter/packages/flutter/lib/src/cupertino/localizations.dart:237:14: Context:
'CupertinoLocalizations.searchTextFieldPlaceholderLabel' is defined here.
[        ] [        ]   String get searchTextFieldPlaceholderLabel;
[        ] [   +2 ms]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[        ] [+5411 ms] lib/page/search_page.dart:369:17: Error: Method not found: 'APIFromRUle.clearNextUrl'.
[   +2 ms] [        ]     APIFromRUle.clearNextUrl();
[        ] [        ]                 ^^^^^^^^^^^^
[        ] [   +7 ms] lib/page/search_page.dart:559:17: Error: Method not found: 'APIFromRUle.clearNextUrl'.
[        ] [        ]     APIFromRUle.clearNextUrl();
[        ] [        ]                 ^^^^^^^^^^^^
[        ] [+3832 ms] lib/model/discover_page_controller.dart:51:17: Error: Method not found: 'APIFromRUle.clearNextUrl'.
[        ] [        ]     APIFromRUle.clearNextUrl();
[        ] [        ]                 ^^^^^^^^^^^^
[        ] [   +2 ms] lib/model/discover_page_controller.dart:183:17: Error: Method not found: 'APIFromRUle.clearNextUrl'.
[        ] [        ]     APIFromRUle.clearNextUrl();
[        ] [        ]                 ^^^^^^^^^^^^
[        ] [   +8 ms] lib/ui/widgets/right_sheet.dart:20:34: Error: No named parameter with the name 'shadowThemeOnly'.
[        ] [        ]         theme: Theme.of(context, shadowThemeOnly: true),
[        ] [        ]                                  ^^^^^^^^^^^^^^^
[        ] [        ] /opt/flutter/packages/flutter/lib/src/material/theme.dart:107:20: Context: Found this candidate, but the arguments
don't match.
[        ] [        ]   static ThemeData of(BuildContext context) {
[        ] [        ]                    ^^
[        ] [+10811 ms] Persisting file store
[        ] [  +28 ms] Done persisting file store
[        ] [   +7 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:278:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:796:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
[        ]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
[        ]            <asynchronous suspension>
[        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:734:32)
[        ]            <asynchronous suspension>
[        ]            #8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:563:16)
[        ]            <asynchronous suspension>
[        ]            #9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:220:32)
[        ]            <asynchronous suspension>
[        ]            #10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1134:12)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:986:27)
[        ]            <asynchronous suspension>
[        ]            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
```

**Comment by mabDc** [comment]
新版本依赖和代码要自己动手，如果你flutter不熟悉，我建议你用`git checkout`切换历史版本，切换到今年八月份的版本，代码会简单易懂，app功能也简单易懂

**Comment by mabDc** [comment]
比如`git checkout c777db9dc3c6dc5094e639ccc9af1ffd56441a34`

**Comment by mabDc** [comment]
谷歌api改很快的，想用最新版，就自己看情况改，看报错提示

**Comment by UniqueDing** [comment]
好的，非常感谢ฅ۶•ﻌ•♡

**Comment by UniqueDing** [comment]
我想寻求一个新的帮助，还可以帮助我一下吗
我下载了编译好的文件eso.linux.deepin，运行时出现这个错误
```bash
flutter: Invalid argument(s): Cannot find executable for xdg-user-dir.flutter: Invalid argument(s): Cannot find executable for xdg-user-dir.
```

**Comment by mabDc** [comment]
不记得了，linux版本我用的deepin 20正式版编译的。

**Comment by mabDc** [comment]
新版本编译是正常的 需要flutter 1.x 大概1.21.x到1.26.x比较容易
